package com.psycodeinteractive.pixabay.presentation.feature.imagelist

import com.psycodeinteractive.pixabay.presentation.navigation.PresentationDestination

object ImageListPresentationDestination : PresentationDestination
